# Executar com: python ../../src/treinar_unsloth.py --treinar 04_treinar_d1.yaml
# Executar com: python ../../src/treinar_unsloth.py --datasets 04_treinar_d1.yaml

# ==========================================================================
# CONFIGURAÇÃO DE TREINAMENTO - Qwen2.5-7B-Instruct (Curriculum d1)
# ==========================================================================
# Ambiente: H100 80GB (1 GPU via Slurm)
# Modo: curriculum (d1: facil-ff, medio, dificil, completo, nbits=4 global)
# Objetivo: CL ascendente com etapa FF no início.
# ==========================================================================
# Ambiente: H100 80GB (1 GPU via Slurm)
# Modo: curriculum (d1q: facil-ff, medio, dificil, completo)
# ==========================================================================

#| =========================================================================
#| MISCELÂNEA
#| =========================================================================
#| Configurações diversas (logs, variáveis de ambiente).
misc:
  pastas_base: 
    - /students/luiz.abatitucci/llms/experimentos/summa-experimento
    - /mnt/d/wsl_dev/llms/experimentos/summa-experimento
    - /opt/app-root/src/luiz/llms/experimentos/summa-experimento
  pastas_modelos:  
    - /students/luiz.abatitucci/models
    - /mnt/d/wsl_ollama/hf-models
    - /opt/app-root/src/luiz/llms/_models


#| =========================================================================
#| CURRICULUM
#| =========================================================================
curriculum:
  #| Saida: Especifica o "Gold Dataset", ou seja, os resultados esperados no gabarito
  saida:
    dataframe: saida/saida_or_235b.parquet
    dataframe_col: resposta
    dataframe_id: chave
    formato: json
    texto_criptografado: false

  #| Entrada: Especifica os dados que o modelo vai receber como prompt
  entrada:
    dataframe: dados/integras_experimento_summa_novos.parquet
    dataset_filtro: {"fold": "<=10"}
    dataframe_col: integra
    dataframe_id: seq_documento_acordao
    prompt_template: dados/prompt_summa_raw.txt
    tag_texto: '<<--TEXTO-->>'
    texto_criptografado: false
    prompt_criptografado: false

  validacao:
    exigir_json_valido: true
    exigir_ids_pareados: false

  #| Divisao: Define as etapas do treinamento (o currículo em si)
  divisao:
  - arquivo: compara/analises_comparacao_summa_q235 (full-base)/divisoes/divisao_Qwen235b_Qwen7b.csv
    dataset_filtro: {"dificuldade": "facil"}
    alias: "fácil-FF"
    tipo: "full"
    learning_rate: 5e-06
    pace_epochs: 2
    bits: 16 # sempre considera 16 no FF
  - arquivo: compara/analises_comparacao_summa_q235 (full-base)/divisoes/divisao_Qwen235b_Qwen7b.csv
    dataset_filtro: {"dificuldade": "medio"}
    alias: "médio"
    tipo: "lora"
    pace_epochs: 2
  - arquivo: compara/analises_comparacao_summa_q235 (full-base)/divisoes/divisao_Qwen235b_Qwen7b.csv
    dataset_filtro: {"dificuldade": "dificil"}
    alias: "difícil"
    tipo: "lora"
    pace_epochs: 2
  - arquivo: compara/analises_comparacao_summa_q235 (full-base)/divisoes/divisao_Qwen235b_Qwen7b.csv
    alias: "completo"
    tipo: "lora"
    pace_epochs: 2

#| =========================================================================
#| MODELO
#| =========================================================================
modelo:
  base_model_name: Qwen2.5-7B-Instruct
  saida: treinos/Qwen2.5-7B-Instruct(d1q)
  ollama: Qwen2.5-7B-Instruct(d1q):latest
  ollama_base: qwen2.5:7b
  ollama_url:

#| =========================================================================
#| TREINAMENTO
#| =========================================================================
treinamento:
  flash_attention_2: true
  full_com_sdpa: true
  liger_kernel: true

  eval_steps: 20%

  batch_size:
    efetivo: 16
    batch_size: 1
  grad_batch_size: 16

  num_train_epochs: 4
  max_seq_length: 32768
  validar_max_seq_length: true
  filtrar_max_seq_length: true

  learning_rate: 2e-05
  save_checkpoints: true
  resume_from_checkpoint: true
  warmup_steps: 5
  weight_decay: 0.01
  optim: adamw_8bit

  lr_scheduler_type: cosine
  seed: 3407

  nbits: 4

  train_on_responses_only: true
