# python ../../src/treinar_unsloth.py --treinar treinar_puil_lora.yaml --reset

misc:
  pastas_base:
  - /students/luiz.abatitucci/llms/experimentos/puil-mini-experimento
  - /mnt/d/wsl_dev/llms/experimentos/puil-mini-experimento
  pastas_modelos:
  - /students/luiz.abatitucci/models
  - /mnt/d/wsl_ollama/hf-models

curriculum:
  saida:
    dataframe: saidas/saida_puil.csv
    dataframe_col: completion
    dataframe_id: id
    formato: texto
    texto_criptografado: false

  entrada:
    dataframe: dados/entrada_puil.csv
    dataframe_col: prompt
    dataframe_id: id
    prompt_template: dados/prompt_puil.txt
    tag_texto: '<<--TEXTO-->>'
    texto_criptografado: false
    prompt_criptografado: false

  validacao:
    exigir_json_valido: false
    exigir_ids_pareados: false

  divisao:
  - arquivo: divisoes/divisao_puil.csv
    alias: "completo"
    tipo: "lora"
    pace_epochs: 1
    batch_size: 1
    max_seq_length: 1024
    learning_rate: 2e-04

modelo:
  base_model_name: Qwen2.5-1.5B-Instruct
  saida: treinos_local/Qwen2.5-1.5B-Instruct(puil_lora)
  ollama: Qwen2.5-1.5B-Instruct(puil_lora):latest
  ollama_base: qwen2.5:1.5b
  ollama_url:

treinamento:
  flash_attention_2: true
  liger_kernel: true
  eval_steps: 20%
  batch_size:
    efetivo: 16
    batch_size: 2
  grad_batch_size: 8
  num_train_epochs: 4
  max_seq_length: 16384
  validar_max_seq_length: true
  learning_rate: 5e-06
  save_checkpoints: true
  resume_from_checkpoint: true
  warmup_steps: 5
  weight_decay: 0.01
  optim: adamw_8bit
  lr_scheduler_type: cosine
  seed: 3407
  nbits: 16
  train_on_responses_only: true
