# ==========================================================================
# Configuração de Extração de Dados do CKAN
# Executar com: python ../../src/util_ckan.py --config config_extracao.yaml
# Visualizar com: python ../../src/util_ckan.py --config config_extracao.yaml --view
# ==========================================================================

# --- Configuração Geral ---
config:
  download_dir: "./downloads_stj"
  atualizar_cache_e_mapas: true

# --- Saída ---
saida:
  arquivo: "./dados/teste_integras_experimento_summa.parquet"
  
  # Mapeia colunas diretamente geradas pelo processo do CKAN
  # Colunas disponíveis padrão CKAN: 
  #   id_mapa, ministro, orgao_julgador, tipo_decisao, ementa, decisao, integra, 
  #   data_publicacao, data_publicacao_iso, numero_registro, seq_documento, processo
  # Colunas auto-padronizadas pelo script:
  #   dt_publicacao, ano, sg_classe, num_registro, seq_documento_acordao
  colunas_ckan:
    processo: processo
    ministro: num_ministro
    dt_publicacao: dt_publicacao
    sg_classe: sg_classe
    integra: integra
    num_registro: num_registro
    seq_documento_acordao: seq_documento_acordao
    ano: ano
    tipo_decisao: tipo_decisao
  
  # Preserva colunas (faz merge via left-join) advindas do arquivo_origem configurado nas extrações
  colunas_origem:
    sg_ramo_direito: sg_ramo_direito
    pasta: pasta
    fold: fold

# --- Sequência de Extrações ---
# Esperados 22237 - mas 202 do grupo 1 são decisões e não acórdãos
extracoes:
  # Grupo 1: Extração dinâmica a partir de um parquet anterior e preservando do merge
  - xtipo: "integras"
    incluir_texto: true
    filtros:
      arquivo_origem: "./dados/pecas_exportadas_textos.parquet"
      #coluna_anos: "ano"
      #anos: [2021, 2022, 2023, 2024, 2025, 2026]
      coluna_documentos: "seq_documento_acordao"
      #tipo_decisao: acordao
    colunas_fixas:
      - extracao: "$hoje"
      
  # Grupo 2: Extração manual com injeção de colunas fixas
  - xtipo: "integras"
    incluir_texto: true
    filtros:
      anos: ["2026"]
      datas: ["2026-05-25"]
      classes: ["AREsp", "REsp", "HC", "RHC"]
      tipo_decisao: acordao
    colunas_fixas:
      - fold: 12
      - pasta: './saidas/<<tipo>>_novos'
      - extracao: "$hoje"

  # Grupo 3: Extração de processos específicos
  - tipo: "integras"
    incluir_texto: true
    filtros:
      # busca pela chave processo (case insensitive) ou numero_registro (12 números string) ou tuplas [registro, data_publicacao] ou [registro, data_publicacao, tipo_decisao]
      processos: ["REsp 2046214", "AREsp 2831077", ["202403674719", "2025-01-03"], ["REsp 2045705", "20230320", "DECISÃO"]]
      documentos: [289154352, 289154346]
    colunas_fixas:
      - fold: 13
      - pasta: "./saidas/<<tipo>>_especificos"
